apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appLabel }}"
spec:
  selector:
    app: "{{ .Values.appLabel }}"
  ports:
  - name: "http"
    protocol: TCP
    port: 5555
    targetPort: 5555
status:
  loadBalancer: {}